### PR TITLE
Feature/multiple step form

### PR DESCRIPTION
**Pull request by tarothanawat**
- Added multiple step form in queue creation
- new module: django-tailwind[reload] automatically reloads the page when something gets updated.
- Fix unique constant bug in Resource model

### CODE REVIEW

**Comment by pannlnwza** [comment]
Good job, but why is the coverage so low?

**Comment by tanasatit** [comment]
Nice step form tora

**Review by pannlnwza — APPROVED** [review]
Ok.

**Comment by tarothanawat** [comment]
I will implement the unit tests next dw

**Pull request merged**
