### PR TITLE
Bugfix/dashboard stats

### PR DESCRIPTION
**Pull request by pannlnwza**
The bug of dashboard stats showing undefined has been fixed. Please review the changes and let me know if any fixes are needed.😚

### CODE REVIEW

**Comment by tarothanawat** [comment]
Good job kub luk P

**Comment by gooddinosaur** [comment]
Good work!

**Comment by tarothanawat** [comment]
Check in time is wrong, but no worry kub. P pan tum dai yu leaw 😃 .

**Comment by pannlnwza** [comment]
Fixed.

**Comment by tarothanawat** [comment]
Good morning good work

**Pull request merged**
