### PR TITLE
Fix/fix statistic page

### PR DESCRIPTION
**Pull request by gooddinosaur**
### Statistic page

- Modify the drop off chart to show no show and cancelled customers instead of removed and cancelled customers.
- Change color of components in drop off chart.

###  General queue manage page
- Fix that search button isn't in search input.

### Added docstrings

- Add docstrings in model files in manager app.
- Add docstrings in view files in manager app.
- Add docstrings in model files in participant app.
- Add docstrings in view files in participant app.

### CODE REVIEW

**Comment by tarothanawat** [comment]
Good fix man.

**Comment by pannlnwza** [comment]
The changes to the chart and the search button fix look good. However, the tests are failing.

**Comment by tanasatit** [comment]
good job krub safe

**Comment by gooddinosaur** [comment]
> The changes to the chart and the search button fix look good. However, the tests are failing.

I have fixed the test already, so it matches the function name in the queue model.

**Pull request merged**
