### PR TITLE
Experiment/change design daisy

### PR DESCRIPTION
**Pull request by gooddinosaur**
- Use DaisyUI and remove bootstrap in base template
- Create basic home page (Need improvement)
- Modify Browse queue page
- Need fixing about Participant in views.py

### CODE REVIEW

**Comment by tarothanawat** [comment]
Daysay You I so good.

**Comment by pannlnwza** [comment]
Nice job lil bro

**Comment by tanasatit** [comment]
nice work!

**Comment by tarothanawat** [comment]
I'm gonna touch you

**Pull request merged**
